# Generated by Django 2.2 on 2019-05-01 19:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_name', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=2, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('ssn', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='SSN')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Profile image')),
            ],
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='first_app.Color'),
        ),
        migrations.CreateModel(
            name='Zip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=50, verbose_name='Zip code')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Country')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='first_app.Town')),
            ],
        ),
    ]
