# Generated by Django 2.2 on 2019-05-03 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20190501_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_color',
            field=models.CharField(default='red', max_length=50, verbose_name='Favorite color'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
