# Generated by Django 2.2.1 on 2019-05-05 11:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_name', models.CharField(max_length=50, verbose_name='Country')),
                ('country_code', models.CharField(max_length=2, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='ISO')),
                ('flag_emoji', models.CharField(max_length=1, unique=True, verbose_name='Flag Emoji')),
                ('calling_code', models.CharField(max_length=4, unique=True, verbose_name='Calling code')),
            ],
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=50, verbose_name='Zip code')),
                ('town', models.CharField(max_length=50, verbose_name='Town')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Country')),
            ],
        ),
    ]
