# Generated by Django 2.2.1 on 2019-05-05 14:39

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postalcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='zip_code',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Zip code'),
        ),
        migrations.AlterUniqueTogether(
            name='postalcode',
            unique_together={('zip_code', 'country')},
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
