# Generated by Django 2.2.1 on 2019-05-07 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20190506_2102'),
        ('castleapartments', '0004_delete_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalcode',
            name='zip_code',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Postal code'),
        ),
        migrations.AddField(
            model_name='postalcode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
