# Generated by Django 2.2.1 on 2019-05-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20190507_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postalcode',
            name='town',
            field=models.CharField(max_length=50, verbose_name='City'),
        ),
    ]
