dist: xenial
language: python
python:
- '3.7'
services:
- postgresql
install:
- pip install -r requirements.txt
before_script:
- psql -c "create database Django;" -U postgres
- psql -c "CREATE USER django WITH PASSWORD 'django_password';" -U postgres
- psql -c "ALTER USER django WITH SUPERUSER;" -U postgres
test:
  adapter: postgresql
  database: Django
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: c/O4Z+Wshpw48z/t1Bzi3BmhpFwGB5ap/x3Lhkbk3jEdgOHZoq8e2LkLNpYHZPeYBbVrqr+pQ/vCWfnLNjXw9gDRZGnGxeZK1QZQjI5hqWS6w+K8vkkQ33CZmQiV47qFMkZc0/NxQJpEi4uHRqwMC723oz2nzJUExGkv8v2jUzpZk0XNycVaEqFZo4BMls6dqC/HjdfPli514dQFFsagiIUpGN9v1NzyNDnMVN7ZWpQRthZzWF7ozAs+X/vZb4Ts2fMfd7vr8SS8jTcQZnHWgLYdmAb8WcCoqVHoWsNggIxP5mHXiZdZmQnrmYaJZI+Z099z4TMOsESmoWvCTJeG0OSsmg17GUCOJwamHyArQvWDDiCvI0ZaEFpsCB+DXOVU9nnvHp6yjzv9mkm1SMQxsTG8TVnsSxl0/+c3pmyH0DXrQAgaIuzzcunYNSxCIy/tcGqupE0deUzjuAePE+DHLXpx15IozrPkJBhbnbEMvvdBfp4BrzL0sGXkmke7UhSyy/OKENaDZsk/pdhvaVNuAMfatXnzzaHBt5QJMQrw6GCl3pvFiiFi3nzNkVKbXdZs/IFXBHbE8pzrvYs/7GC28lZH1UdFYskhv0CgY2zHelMrksde933LtB+8giw75Cbx57U1xG9dTb1SZsvYzcK5kQZWOb1e5JJvX7OnD/6tUQ0=
  app: still-stream-97107
  on:
    repo: GudniNatan/SC-T-220-VLN2
