dist: xenial
language: python
python:
    - "3.7"

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database Django;' -U postgres
  - psql -c "CREATE USER django WITH PASSWORD 'django_password';" -U postgres

test:
  adapter: postgresql
  database: Django

# command to run tests
script:
  - python manage.py test