# Generated by Django 2.2.1 on 2019-05-08 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0004_auto_20190507_1423'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('apt_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apt. number')),
                ('appraisal', models.BigIntegerField(verbose_name='Appraisal')),
                ('num_rooms', models.IntegerField(verbose_name='Bedrooms')),
                ('num_bathrooms', models.IntegerField(verbose_name='Bathrooms')),
                ('size', models.FloatField(verbose_name='Size (m²)')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('listing_date', models.DateTimeField(auto_now=True, verbose_name='Listing date')),
                ('sold_date', models.DateField(blank=True, null=True, verbose_name='Date sold')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed by staff')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Apartment')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='apartments/', verbose_name='Image')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Apartment', verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.ApartmentType', verbose_name='Apartment type'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='postal_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.PostalCode', verbose_name='Postal code'),
        ),
    ]
