# Generated by Django 2.2.1 on 2019-05-09 12:08

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='apartments/'),
        ),
    ]
