# Generated by Django 2.2.1 on 2019-05-09 13:01

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_auto_20190509_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='apartments/', verbose_name='Image'),
        ),
    ]
