# Generated by Django 2.2.1 on 2019-05-09 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_auto_20190509_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='description_truncation_length',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='apartmentimage',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Apartment', verbose_name='Apartment Image'),
        ),
    ]
