# Generated by Django 2.2.1 on 2019-05-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_apartment_garage_parking_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='year_build',
            field=models.IntegerField(default=0, verbose_name='Year built'),
        ),
    ]
