# Generated by Django 2.2.1 on 2019-05-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_apartment_year_build'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='year_build',
            new_name='year_built',
        ),
    ]
