# Generated by Django 2.2.1 on 2019-05-06 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castleapartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='apt_number',
            field=models.CharField(max_length=50, null=True, verbose_name='Apt. number'),
        ),
    ]
