# Generated by Django 2.2.1 on 2019-05-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castleapartments', '0002_auto_20190506_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='apt_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apt. number'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_img',
            field=models.ImageField(upload_to='images/', verbose_name='Profile image'),
        ),
    ]
