# Generated by Django 2.2.1 on 2019-05-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('castleapartments', '0003_auto_20190507_1423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
