# Generated by Django 2.2.1 on 2019-05-07 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20190507_1423'),
        ('castleapartments', '0005_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None, verbose_name='Image')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castleapartments.ApartmentType', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('apt_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apt. number')),
                ('appraisal', models.BigIntegerField(verbose_name='Appraisal')),
                ('num_rooms', models.IntegerField(verbose_name='Bedrooms')),
                ('num_bathrooms', models.IntegerField(verbose_name='Bathrooms')),
                ('size', models.IntegerField(verbose_name='Size (m²)')),
                ('description', models.TextField(verbose_name='Description')),
                ('apartment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castleapartments.ApartmentType', verbose_name='Apartment type')),
                ('postal_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.PostalCode', verbose_name='Postal code')),
            ],
        ),
    ]
