# Generated by Django 2.2.1 on 2019-05-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castleapartments', '0006_apartment_apartmentimage_apartmenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmenttype',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
