# Generated by Django 2.2.1 on 2019-05-07 21:33

import castleapartments.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('castleapartments', '0008_auto_20190507_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_number', models.CharField(max_length=22, validators=[castleapartments.validators.credit_card_validator])),
                ('credit_card_expiration_date', models.DateField(verbose_name='Expiration date')),
                ('credit_card_cvv', models.CharField(max_length=4, verbose_name='CVV')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_date', models.DateTimeField(auto_now=True, verbose_name='Listing date')),
                ('sold_date', models.DateField(blank=True, null=True, verbose_name='Date sold')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed by staff')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castleapartments.Apartment')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Seller')),
            ],
        ),
        migrations.AlterField(
            model_name='apartmentimage',
            name='image',
            field=models.ImageField(upload_to='apartments/', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now=True, verbose_name='Offer request date')),
                ('request_amount', models.IntegerField(verbose_name='Offer request amount')),
                ('accepted', models.BooleanField(default=False, verbose_name='Accepted')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed by staff')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('credit_card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='castleapartments.CreditCard', verbose_name='')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='castleapartments.Listing', verbose_name='Listing')),
            ],
        ),
    ]
