# Generated by Django 2.2.1 on 2019-05-08 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apartments', '0001_initial'),
        ('castleapartments', '0011_auto_20190508_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now=True, verbose_name='Offer request date')),
                ('request_amount', models.IntegerField(verbose_name='Offer request amount')),
                ('accepted', models.BooleanField(default=False, verbose_name='Accepted')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed by staff')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('credit_card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='castleapartments.CreditCard', verbose_name='')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.Listing', verbose_name='Listing')),
            ],
        ),
    ]
