# Generated by Django 2.2.1 on 2019-05-10 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('castleapartments', '0013_auto_20190509_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='credit_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='castleapartments.CreditCard', verbose_name='Credit card'),
        ),
    ]
