# Generated by Django 2.2.1 on 2019-05-14 17:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apartments', '0008_auto_20190514_1717'),
        ('castleapartments', '0014_auto_20190510_1550'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('buyer', 'listing')},
        ),
    ]
