# Generated by Django 2.2.1 on 2019-05-14 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('castleapartments', '0015_auto_20190514_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='credit_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='castleapartments.CreditCard', verbose_name='Credit card'),
        ),
    ]
