# Generated by Django 2.2.1 on 2019-05-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castleapartments', '0017_auto_20190515_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='request_date',
            field=models.DateTimeField(verbose_name='Offer request date'),
        ),
    ]
